apiVersion: v1
entries:
  yet-another-secrets-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-09-19T12:35:04.966829055Z"
    description: A Kubernetes operator for managing secrets between Kubernetes and
      AWS SecretsManager
    digest: 598b65fd410adfb49b995749451d0bf4a3b1240fcf7695f42e2de46a9176108b
    name: yet-another-secrets-operator
    type: application
    urls:
    - https://snaax.github.io/yet-another-secrets-operator/charts/yet-another-secrets-operator-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-19T12:35:04.966226057Z"
