apiVersion: yet-another-secrets.io/v1alpha1
kind: ASecret
metadata:
  name: asecret-sample
  namespace: yaso
spec:
  targetSecretName: my-secret
  awsSecretPath: /path/to/aws/secret
  onlyImportRemote: true # Only import from AWS, don't create if missing. Ignore data content if set to true
  data:
    username:
      value: admin
    password:
      generatorRef:
        name: password-generator
    existingApiKey:
      onlyImportRemote: true  # Only import from AWS, don't create if missing
    apiKey:
      value: ""
    dbPassword:
      generatorRef:
        name: strong-password-generator
