---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "yet-another-secrets-operator.fullname" . }}-role
  labels:
    {{- include "yet-another-secrets-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - yet-another-secrets.io
  resources:
  - agenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yet-another-secrets.io
  resources:
  - agenerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - yet-another-secrets.io
  resources:
  - agenerators/finalizers
  verbs:
  - update
- apiGroups:
  - yet-another-secrets.io
  resources:
  - asecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yet-another-secrets.io
  resources:
  - asecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - yet-another-secrets.io
  resources:
  - asecrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "yet-another-secrets-operator.fullname" . }}-rolebinding
  labels:
    {{- include "yet-another-secrets-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yet-another-secrets-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "yet-another-secrets-operator.serviceAccountName" . }}
  namespace: {{ include "yet-another-secrets-operator.namespace" . }}